### ISSUE TITLE
有声音，但是视频画面卡死

### ISSUE THREAD

**Issue by kkkkk5G** [Bepartofyou/janus-gateway-live#1]
你好，我在研究janus的rtmp推流方案，找到了您的开源模块，非常开心，感谢您无私的分享。
我在使用测试的过程中发现，虽然流能正常推送出去，但是视频画面会卡在某一帧不动，只有声音是正常的。或许是我操作的有问题，请问您知道原因吗？

**Comment by yinjianfeng** [comment]
我这边跑了，没什么大问题，但就是推流的时候延迟特别大

**Comment by kkkkk5G** [comment]
> 我这边跑了，没什么大问题，但就是推流的时候延迟特别大

感谢您的回复，我后来发现是我这边推流的编码有问题，兄弟方便加个联系方式吗 我的qq 1210399613

**Comment by Bepartofyou** [comment]
延时是多个方面的，比如编码延时，相应的就会有解码延时，然后gop间隔，janus的h264默认是15s一次IDR，那中间推流的话肯定是没法播放的，可以自己调价这个间隔，比如调到1s看看。

这个功能代码引入的延时是有的大概2s还是3s的忘记了，是为了使用方便不会出现网络抖动之类引起的问题，一个jitter缓存，一个是rtmp帧缓存，这个是有办法清掉的，自己可以想一下怎么去掉
